### PR TITLE
Update readme and final test for 3.2.0

### PR DESCRIPTION
**Pull request by soylentOrange**
* Updated the readme to match the new release.
* made some more tests with different versions of python, vtk, paraview
* ran a (successful) test (tests/test.py) on several frd files

@imirzov & @fsimonis , yes, I think it's worth a new release: 3.2.0
After some additional testing, I've prepared a new PR to update the documentation regarding the current interface.
After this is merged, the new release can be published.

In my opinion the list of improvements is:
* ~~Added vtkhdf writer~~ (that's not in the code)
* Fix syntax warning invalid escape sequence on python 3.13
* Made the development version installable by pip
* Add alias scripts for converting to formats
* Add PyPi publishing workflow
* Turned into installable package
* Improvements in von Mises and principal stress calculations
* streamline import of Converter (i.e. `from ccx2paraview import Converter`)
* fix broken pvd-file (missing '.' in '.vtu')
* added description in readme: how to convert to a vtkhdf-file

BR,
Robert

### CODE REVIEW

**Comment by fsimonis** [comment]
I tried to install the package using pipx, which succeeds, but it doesn't install vtk. Thus running the commands fails.

```console
$ pipx install https://github.com/soylentOrange/ccx2paraview/archive/refs/heads/prepare-3.2.0-release.zip
 installed package ccx2paraview 0.0.1, installed using Python 3.11.9
  These apps are now globally available
    - ccx2paraview
    - ccxToVTK
    - ccxToVTU
done!
$ ccx2paraview
Traceback (most recent call last):
  File "~/.local/pipx/venvs/ccx2paraview/lib/python3.11/site-packages/ccx2paraview/common.py", line 23, in <module>
    from vtk import (vtkUnstructuredGridWriter, vtkXMLUnstructuredGridWriter, \
ModuleNotFoundError: No module named 'vtk'
Install either vtk ar paraview.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "~/.local/bin/ccx2paraview", line 5, in <module>
    from ccx2paraview.cli import main
  File "~/.local/pipx/venvs/ccx2paraview/lib/python3.11/site-packages/ccx2paraview/__init__.py", line 3, in <module>
    from . import common
  File "~/.local/pipx/venvs/ccx2paraview/lib/python3.11/site-packages/ccx2paraview/common.py", line 27, in <module>
    raise ImportError("Module vtk is not available!") from e
```

Installing vtk fixes the issue:

```console
$ pipx inject ccx2paraview vtk
  injected package vtk into venv ccx2paraview
done!
$ ccx2paraview
usage: ccx2paraview [-h] filename {vtk,vtu} [{vtk,vtu} ...]
ccx2paraview: error: the following arguments are required: filename, format
```

So vtk needs to be added to the dependencies in the ´myproject.toml´:

https://github.com/soylentOrange/ccx2paraview/blob/ea745ba06645c958ac8cb764e9142a3ca2bdaad1/pyproject.toml#L8-L10

@soylentOrange Can you fix this on the release branch?

**Comment by soylentOrange** [comment]
@fsimonis it seems that my testing wasn't thorough enough...
Actually, I removed vtk from the dependencies as it seems to breaks paraview (in python 3.13). 
I added an exception in common.py to instruct users to have either vtk or paraview installed when trying to run the converter:
```python
Traceback (most recent call last):
  File "~/.local/pipx/venvs/ccx2paraview/lib/python3.11/site-packages/ccx2paraview/common.py", line 23, in <module>
    from vtk import (vtkUnstructuredGridWriter, vtkXMLUnstructuredGridWriter, \
ModuleNotFoundError: No module named 'vtk'
Install either vtk or paraview. 
```

I'll try different constellations of pip, pipx and conda to see the effects and will update the branch on my fork of ccx2paraview. 

BR,
Robert

**Comment by soylentOrange** [comment]
I'll close PR https://github.com/calculix/ccx2paraview/pull/50 for now and will create a new one, when I think that it's working with pipx as well.

**Comment by fsimonis** [comment]
If installing vtk is an issue, then adding it as an optional dependency may be a solution.
This way, one can it via pipx without injecting vtk.

https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#optional-dependencies

```
dependencies = [
    "vtk[VTK]"
]
```

`pipx install ccx2paraview[VTK]`

**Pull request closed without merging**
